# Tensores 

Tensores são a estrutura de dados primária que o TensorFlow usa para operar no grafo computacional. Podemos declarar esses tensores como **variáveis**, **constantes** e alimentá-los com **placeholders**. 

## Declarando tensores

Primeiro, precisamos saber como criar tensores. Existem várias formas de criar tensores no TensorFlow:

In [16]:
import tensorflow as tf

sess = tf.Session()

TensorFlow foi construído em função para criar tensores para uso em variáveis. Por exemplo, podemos criar um tensor preenchido com zero de forma predefinida usando a função tf.zeros () como segue.

In [27]:
ter_zero = tf.zeros([2, 3, 5])
#Podemos avaliar tensores com a chamada de um método run() em nossa sessão.
sess.run(ter_zero)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)

In [28]:
#Criar um tensor preenchido de zeros

ter_ones = tf.ones([3, 2, 4])

In [29]:
#Criar um tensor preenchido de uma constante

ter_conts = tf.fill([4, 4, 4], 0.2)

In [30]:
#Criar um tensor preenchido com constantes já existentes

ter_consts2 = tf.constant([[45, 56, 5], 
                        [3, -3, -4]])

In [31]:
#Tem como iniciarmos tensores com base em outras variáveis

zeros_similar = tf.zeros_like(ter_consts2)
ones_similar = tf.ones_like(ter_consts2)

print(zeros_similar)
print(ones_similar)
print(ter_consts2)

Tensor("zeros_like_4:0", shape=(2, 3), dtype=int32)
Tensor("ones_like_4:0", shape=(2, 3), dtype=int32)
Tensor("Const_2:0", shape=(2, 3), dtype=int32)


## Criando Tensores Baseados em Sequências e Intervalos

Também podemos criar tensores a partir de funções de geração de sequência. As funções `linspace()` e `range()` operam de maneira muito semelhante aos equivalentes python/numpy.

In [24]:

# Linspace no TensorFlow
linear_tens = tf.linspace(start=0.0, stop=1.0, num=3) # gera [0.0, 0.5, 1.0]

# Range no TensorFlow
sequence_tens = tf.range(start=6, limit=15, delta=3) # gera [6, 9, 12]

print(sess.run(linear_tens))
print(sess.run(sequence_tens))

[0.  0.5 1. ]
[ 6  9 12]


## Valores Aleatórios

Podemos também inicializar tensores com números aleatórios:

In [26]:
rnorm_tens = tf.random_normal([2, 5], mean=0.0, stddev=1.0)
runif_tens = tf.random_uniform([2, 5], minval=0, maxval=4)

print(sess.run(rnorm_tens))
print(sess.run(runif_tens))

[[ 0.93908113 -0.09634297 -0.12126986 -2.1226382   0.8582718 ]
 [-0.43361267 -1.4046769   0.1943809  -1.0293678   1.1101444 ]]
[[0.15634108 3.7974439  3.017315   2.5253901  0.47274923]
 [2.9618983  0.7337756  3.1901798  3.7352867  0.73898315]]


# Usando placeholder e Variáveis

Placeholders e variáveis são ferramentas-chave para usar gráficos computacionais no TensorFlow. Devemos entender a diferença e quando melhor utilizá-las em nosso benefício.

* **TensorFlow Variables (tf.Variables()):**  Quando se treina um modelo, usa-se variáveis para manter e atualizar os parâmetros. As variáveis são buffers na memória contendo tensores.

    * Pode atualuzar os peso/bias durante a otimização para minimizar uma função de perda (erro).

* **TensorFlow Placeholders (tf.Placeholders()):** Nós “falsos” que fornecem pontos de entrada de dados para o grafo computacional  durante tempo de execução.
    * Os Placeholders  são objetos que permitem o fornecimento de dados de um tipo e forma específicos. 
    * São usados para passar os dados de treinamento para TensorFlow durante o treinamento. Caso não especifique um valor em tempo de execução para Placeholders, é gerado uma exceção (pode ocasionar um erro se não tratado).
    
## Manipulando Variáveis

A principal maneira de criar uma variável é usando a função `Variable()`, que usa um tensor como entrada e gera uma variável. Ainda precisamos inicializar a variável. Iniciar a variável a acresta com os métodos correspondentes no grafo computacional.


In [37]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(my_var)

FailedPreconditionError: Attempting to use uninitialized value Variable_5
	 [[Node: _retval_Variable_5_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_5)]]