# Declarando Operações

Agora precisamos aprender sobre as outras operações que podemos adicionar a um gráfico do TensorFlow.

Além das operações aritméticas padrão, o TensorFlow nos fornece mais operações das quais devemos estar cientes. Precisamos saber como usá-los antes de prosseguir:

In [2]:
import tensorflow as tf

## Operaçoes aritimeticas

Os algoritmos de aprendizado de máquina são fundamentalmente matemáticos, e o TensorFlow fornece uma grande variedade de métodos para executar operações matemáticas em tensores.


| Método                    | Descrição                                   |
|---------------------------|---------------------------------------------|
| add(x, y, name=None)      | Adiciona dois tensores                      |
| subtract(x, y, name=None) | Subtrai dois tensores                       |
| multiply(x, y, name=None) | Multiplica dois tensores                    |
| divide(x, y, name=None)   | Divide os elementos de dois tensores        |
| div(x, y, name=None)      | Divide os elementos de dois tensores        |
| add_n(inputs, name=None)  | Adiciona tensores múltiplos                 |
| scalar_mul(scalar, x)     | Escala um tensor por um valor escalar       |
| mod(x, y, name=None)      | Executa a operação do módulo                |
| abs(x, name=None)         | Calcula o valor absoluto                    |
| negative(x, name=None)    | Nega os elementos do tensor                 |
| sign(x, name=None)        | Extrai os sinais dos elementos dos tensores |
| reciprocal(x, name=None)  | Calcula os recíprocos                       |

As primeiras quatro funções executam aritmética elementar.

In [4]:
#definimos nosso grafo 
graph = tf.Graph()

with graph.as_default():#Abre o grafo para definimos as variáveis (tensores) operações nós
    a = tf.constant([3., 3., 3.])
    b = tf.constant([2., 2., 2.])
    
    #Adicionando operações
    sum1 = tf.add(a, b)                 # [ 5. 5. 5. ]
    diff = tf.subtract(a, b)           # [ 1. 1. 1. ]
    prod = tf.multiply(a, b)           # [ 6. 6. 6. ]
    quot = tf.divide(a, b)             # [ 1.5 1.5 1.5 ]

with tf.Session(graph=graph) as sess:
    print(sum1.eval())
    print(diff.eval())
    print(prod.eval())
    print(quot.eval())


[5. 5. 5.]
[1. 1. 1.]
[6. 6. 6.]
[1.5 1.5 1.5]


Os algoritmos podem executar operações idênticas usando operadores regulares do Python, como +, -, *, / e //.

In [7]:
#definimos nosso grafo 
graph1 = tf.Graph()

with graph1.as_default():#Abre o grafo para definimos as variáveis (tensores) operações nós
    a = tf.constant([3., 3., 3.])
    b = tf.constant([2., 2., 2.])
    
    #Adicionando operações
    sum1 = tf.add(a, b)     # [ 5. 5. 5. ]
    sum2 = a + b            # [ 5. 5. 5. ]

with tf.Session(graph=graph1) as sess:
    print(sum1.eval())
    print(sum2.eval())

[5. 5. 5.]
[5. 5. 5.]


## Operações vetoriais e matriciais no tensorflow

Em aprendizado de máquina armazenam uma grande quantidade de dados em vetores (tensores unidimensionais) e matrizes (tensores bidimensionais). Para processar esses dados, o TensorFlow fornece muitas funções que operam em vetores e matrizes. A tabela a seguir lista essas funções e fornece uma descrição de cada uma delas.

| Função                                                                                                                                                                                 | Descrição                                                                                                 |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|
| tensordot(a, b, axes, name=None)                                                                                                                                                       | Retorna a soma dos produtos para os elementos nos eixos especificados                                     |
| cross(a, b, name=None)                                                                                                                                                                 | Retorna o produto cruzado por elementos                                                                   |
| diag(diagonal, name=None)                                                                                                                                                              | Retorna uma matriz com os valores diagonais fornecidos, outros valores definidos como zero                |
| trace(x, name=None)                                                                                                                                                                    | Retorna a soma dos elementos da diagonal                                                                  |
| transpose(x,            perm=None,           name='transpose')                                                                                                                         | Alterna linhas e colunas                                                                                  |
| eye(num_rows,      num_columns=None,     batch_shape=None,     dtype=tf.float32,     name=None)                                                                                        | Cria uma matriz de identidade com a forma e o tipo de dados fornecidos                                    |
| matmul(a, b,        transpose_a=False,        transpose_b=False,        adjoint_a=False,        adjoint_b=False,        a_is_sparse=False,        b_is_sparse=False,        name=None) | Retorna o produto das duas matrizes de entrada                                                            |
| norm(tensor,      ord='euclidean',      axis=None,      keep_dims=False,      name=None)                                                                                               | Retorna a norma do eixo dado do tensor de entrada com a ordem especificada                                |
| matrix_solve(A, b,              adjoint=None,name=None)                                                                                                                                | Retorna o tensor x, tal que Ax = b , onde A é uma matriz e b é um vetor                                   |
| qr(input, full_matrices=None,name=None)                                                                                                                                                | Retorna os autovetores e autovalores da matriz ou matrizes                                                |
| svd(tensor,     full_matrices=False,     compute_uv=True,     name=None)                                                                                                               | Fatores da matriz em uma matriz unitária, uma matriz diagonal e a transposta conjugada da matriz unitária |
| einsum(equation, *inputs)                                                                                                                                                              | Executa uma operação matemática customizada                                                               |

In [11]:
#definimos nosso grafo 
graph2 = tf.Graph()

with graph1.as_default():#Abre o grafo para definimos as variáveis (tensores) operações nós
    t1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]) #3x2
    t2 = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]) #2x3

    t1xt2 = tf.matmul(t1, t2)    # [[ 22. 28.], [ 49. 64.]]


with tf.Session(graph=graph1) as sess:
    print(t1xt2.eval())

[[22. 28.]
 [49. 64.]]
